export const STRING = {
  log_in: 'Login',
  create_an_account: 'CREATE AN ACCOUNT',
  or: 'OR',
  signUp: 'SIGN UP',
  pickPhoto: 'PICK PHOTO',
  pleaseWait: 'Please wait...',
  loading: 'Loading...',
  googleText: 'Sign in with Google',
  email: 'Email',
  email_username: 'Email or username',
  pseudo: 'Pseudo',
  fullName: 'Full Name',
  name: 'Name',
  phone: 'Mobile',
  password: 'Password',
  forgot_password: 'Forgot Password ?',
  signINTo: 'Sign In to',
  signUPTo: 'Sign Up to',
  nameHint: 'John Doe',
  firstNameHint: 'John',
  lastNameHint: 'Doe',
  phoneHint: '123-456-7890',
  emailHint: 'yourname@abc.com',
  appName: 'ClubXtreme',
  passwordHint: '********',
  dontaccount: "Don't have an account? ",
  alreadyAccount: 'Already have an account? ',
  sign_Up: 'Sign Up',
  invalidEmailAddress: 'Invalid Email',
  invalidMobileNumber: 'Invalid Mobile Number',
  fieldRequired: 'Field is required',
  welcome_to: 'Welcome to',
  get_started: 'Get Started',
  login_create_account: 'Log In / Create Account',
  register_now: 'Register Now',
  skip: 'SKIP',
  next: 'Next',
  add_review: 'Add Review',
  logoutMessage:
    'Your account is logged out, that because your account is blocked or deleted\nMore information contact the admin',

  fine_print_1:
    'Voucher Cannot be combined or used with any other offers or promotions',
  fine_print_2: 'Standard Fine Print apply for all the offers in app',
  fine_print_3:
    'General Terms and Conditions and User’s Terms and Conditions apply',
  how_to_red_1: 'Expiry: 30 days from purchase',
  how_to_red_2: 'Standard Redeem procedure apply',
  how_to_red_3: 'No booking required, unless stated by Business',
  how_to_red_4: 'Payment method will be Cash or Credit/Debit Card.',
  how_to_red_5: 'Credit/Debit Card may require at the time of claim the deal',
  how_to_red_6:
    'Present printed Invoice,  app purchase on arrival, or call prior for confirmation',
  how_to_red_7: 'Download free Bunch Of Deals app on Google and IOS.',

  transaction_history: 'Transaction History',
  tell_friend: 'Tell Your Friend',
  notifications: 'Notifications',
  view_invoice: 'View Invoice',
  invoice: 'Invoices',
  settings: 'Settings',
  logout: 'Log out',
  transaction_id: 'Transaction ID:',

  stores: 'Stores',
  offers: 'Offers',
  recent: 'Recent',
  nearby: 'Nearby',
  order: 'ORDER',

  whoops: 'Whooops!',
  network_not_available: "Couldn't load data from server",
  retry: 'Retry',
  // internal fields / variables name
  onBoardComplete: 'ON_BOARD_COMPLETE',
  userEmail: 'USER_EMAIL',
  initConfig: 'INIT_CONFIG',
  userNotificationPref: 'USER_NOTIFICATION_PREF',

  // order by filter
  ORDER_RECENT: 'recent',
  ORDER_NEARBY: 'nearby',
  ORDER_TOP_RATED: 'top_rated',
  ORDER_NEARBY_TOP_RATED: 'nearby_top_rated',

  // api parameters
  API_LATITUDE: 'latitude',
  API_LONGITUDE: 'longitude',
  API_ORDER_BY: 'order_by',
  API_OFFER_IDS: 'offer_ids',
  API_TOKEN: 'token',
  API_MAC_ADR: 'mac_adr',
  API_LIMIT: 'limit',
  API_PAGE: 'page',
  API_SEARCH: 'search',
  API_DATE: 'date',
  API_TIME_ZONE: 'timezone',
  API_RADIUS: 'radius',
  API_CATEGORY_ID: 'category_id',
  API_STORE_ID: 'store_id',

  REQUEST_RANGE_RADIUS: -1,
  distance_max_display_route: 500000,

  // on demand variables
  CURRENT_LAT: 0.0,
  CURRENT_LONG: 0.0,
  FCM_TOKEN: '',
  MAC_ADR: '00:02:00:00:00',

  CAN_ACCESS_LOCATION: false,
  IS_LOGGED_IN: false,
  SEARCH_LOCATION: 'Current Location',

  /// constant -
  ANDROID_APP_ID: '477b00c095ab859fff3e010d1ce96e4d',
};
