export const STRING = {
  log_in: 'Login',
  create_an_account: 'CREATE AN ACCOUNT',
  or: 'OR',
  signUp: 'SIGN UP',
  pickPhoto: 'PICK PHOTO',
  pleaseWait: 'Please wait...',
  loading: 'Loading...',
  googleText: 'Sign in with Google',
  email: 'Email',
  email_username: 'Email or username',
  pseudo: 'Pseudo',
  fullName: 'Full Name',
  name: 'Name',
  phone: 'Mobile',
  password: 'Password',
  forgot_password: 'Forgot Password ?',
  signINTo: 'Sign In to',
  signUPTo: 'Sign Up to',
  nameHint: 'John Doe',
  firstNameHint: 'John',
  lastNameHint: 'Doe',
  phoneHint: '123-456-7890',
  emailHint: 'yourname@abc.com',
  appName: 'ClubXtreme',
  passwordHint: '********',
  dontaccount: "Don't have an account? ",
  alreadyAccount: 'Already have an account? ',
  sign_Up: 'Sign Up',
  invalidEmailAddress: 'Invalid Email',
  invalidMobileNumber: 'Invalid Mobile Number',
  fieldRequired: 'Field is required',
  welcome_to: 'Welcome to',
  get_started: 'Get Started',
  login_create_account: 'Log In / Create Account',
  register_now: 'Register Now',
  skip: 'SKIP',
  next: 'Next',

  transaction_history: 'Transaction History',
  tell_friend: 'Tell Your Friend',
  notifications: 'Notifications',
  view_invoice: 'View Invoice',
  invoice: 'Invoices',
  settings: 'Settings',
  logout: 'Log out',
  transaction_id: 'Transaction ID:',

  stores: 'Stores',
  offers: 'Offers',
  recent: 'Recent',
  nearby: 'Nearby',
  order: 'ORDER',

  whoops: 'Whooops!',
  network_not_available: "Couldn't load data from server",
  retry: 'Retry',
  // internal fields / variables name
  onBoardComplete: 'ON_BOARD_COMPLETE',
  userEmail: 'USER_EMAIL',

  // order by filter
  ORDER_RECENT: 'recent',
  ORDER_NEARBY: 'nearby',
  ORDER_TOP_RATED: 'top_rated',
  ORDER_NEARBY_TOP_RATED: 'nearby_top_rated',

  // api parameters
  API_LATITUDE: 'latitude',
  API_LONGITUDE: 'longitude',
  API_ORDER_BY: 'order_by',
  API_OFFER_IDS: 'offer_ids',
  API_TOKEN: 'token',
  API_MAC_ADR: 'mac_adr',
  API_LIMIT: 'limit',
  API_PAGE: 'page',
  API_SEARCH: 'search',
  API_DATE: 'date',
  API_TIME_ZONE: 'timezone',
  API_RADIUS: 'radius',
  API_CATEGORY_ID: 'category_id',
  API_STORE_ID: 'store_id',

  REQUEST_RANGE_RADIUS: -1,
  distance_max_display_route: 500000,

  // on demand variables
  CURRENT_LAT: 0.0,
  CURRENT_LONG: 0.0,
  FCM_TOKEN: '',
};
